export const content = {
  "terms-and-conditions": {
    type: "static",
    ar: {
      header: "<h2 style={{ padding: 0, margin: 0 }}>البنود و الشروط </h2>",
      body: " <p style=margin-left:0>أولاً : سياسة الخصوصية</p><p style=margin-left:0>يمكنك التأكد من أمان وسرية بياناتك الشخصية التي تقدمها لموقع الخباز حيث نضمن سريتها التامة تجاه أي طرف آخر فيما عدا الجهات الحكومية إذا لزم الأمر</p><p style=margin-left:0>ثانياً : حقوق الملكية الفكرية والعلامات التجارية</p><p style=margin-left:0>&nbsp;</p><ul><li>جميع المحتوى على الموقع، بما في ذلك، ولكن ليس على سبيل الحصر، النص والرسومات والشعارات والصور ومصنفات البيانات والبرمجيات وتجميع كل ذلك ('المحتوى') هي ملك لـ 'الخباز' لا يجوز نسخها أو استخدامها دون موافقة خطية من الشركة</li><li>-العلامات التجارية والشعارات هي علامات مسجلة لـ 'الخباز' ، في جمهورية مصر العربي</li><li>لا يجوز استخدام أي جزء من الموقع ، استنساخه، تكراره، نسخه، بيعه، إعادة بيعه، الوصول إليه، أو تعديله، أو خلاف ذلك استغلاله، كليًا أو جزئيًا، لأي غرض بدون موافقة خطية مسبقة من الشركة</li></ul><p style=margin-left:0>ثالثاً : المحتوى</p><p style=margin-left:0>&nbsp;</p><ul><li>يقوم الموقع بحفظ ملف تعريف يحتوي بيانات تعريفية لتمييزك عن غيرك و للتعرف عليك عند العودة لزيارة التطبيق مرة أخرى</li><li>لا يكشف الموقع ملفات تعريف الارتباط الخاصة بالزائر إلى أي طرف ثالث باستثناء المذكورين هنا في سياسة الخصوصية، إلا إذا استلزم إجراء قضائي ذلك، مثل مذكرة تفتيش أو أمر من المحكمة</li></ul><p style=margin-left:0>رابعا: استخدام الموقع بغرض عرض وتسويق وبيع منتجات وخدمات 'الخباز' وخدمة عملائها والتواصل معهم</p><p style=margin-left:0>&nbsp;</p><ul><li>عند الدفع على الموقع بأي وسية تم توفيرها عليه فإن جميع من قام بالشراء سواء ببطاقة ائتمان أو بطاقة دفع مسبقا أو أي بطاقة دفع أخرى سارية الصلاحية فأنه يتم سحب القيمة الكلية لسعر المنتج أو المنتجات المشتراه شاملاً الضرائب الرسمية.</li><li>-مع بداية تأكيدك لشراء أي من المنتجات، فأنت تسمح لـ 'الخباز' بالتحري- بالاستعانة بطرف ثالث - عن حسابك وكفاية رصيدك وذلك للتأكد من هويتك وضمان سلامة عملية الدفع.</li><li>في حال تغيير المعلومات الشخصية الخاصة بك، ننصح بتحديث بياناتك على الموقع – ويكون لنا الحق في إجراء أية تعديلات على شروط الخدمة بحسب تقديرنا الخاص ووفقًا لما نراه مناسباً.</li></ul><p style=margin-left:0>- خامساً : التسوق على الموقع</p><p style=margin-left:0>عند عمل طلبية شراء من خلال الموقع، أنت تقوم بشراء المنتج مقابل السعر المذكور, علما ان جميع الأسعار الموجودة غير شاملة ضريبة القيمة المضافة.-جميع الطلبيات تخضع للموافقة وتوفّر المنتج ولا يحق لمستخدم الموقع المطالبة بأي تعويض في حال عدم إمكانية تلبية طلبه أو عدم توفر المنتج الذي اشتراه وله الحق في استعادة ما دفعه مخصوماً منه أي رسوم إدارية تخص بوابة الدفع الإلكتروني أو حسابه الإئتماني الخاص به لدى البنك المزود للبطاقة</p><p style=margin-left:0>سادسا وسائل وشروط الدفع</p><p style=margin-left:0>&nbsp;</p><ul><li>-طرق دفع متنوعة تشمل الدفع عند الاستلام ، وكذلك بواسطة بطاقات الائتمان.</li><li>ويمكن التواصل والإتصال بنا خلال ساعات العمل علي الخط الساخن 01205977776.</li><li>حيث مواعيد العمل لجميع الفروع من الساعة 8 صباحا حتى الساعة 12 منتصف الليل و قسم الدليفرى متاح من الساعة 8 صباحا الى الساعة 11 مساءا.</li></ul>",
    },
    en: {
      header: "<h2 style={{ padding: 0, margin: 0 }}>Terms and Conditions</h2>",
      body: " <div><h4 style={{ color: '$primary' }}>First: Privacy Policy</h4><p>You can ensure the security and confidentiality of your personal data that you provide to freshly fit's website, as we guarantee its complete confidentiality towards any other party except government agencies if necessary.</p></div>",
    },
  },
  "delivery-policy": {
    type: "static",
    ar: {
      header: "<h2 style={{ padding: 0, margin: 0 }}>سياسة التوصيل </h2>",
      body: "<ul><li><p>- مدة توصيل الطلب تكون في خلال فترة ما بين (1) ساعة الي (3) ساعات و من الممكن أن تزيد في أوقات الذروة وفي المواسم.</p><p>- يمكنكم متابعة الطلبات من خلال الموقع او من خلال الاتصال بالخط الساخن 01205977776 .</p><p>- لأي طلبات أو استفسارات تخص المنتجات أو الخدمات كالشحن والتوصيل أو الشكاوي والاقتراحات يُرجى مراسلتنا عليinfo@alkhbaz.com</p></li></ul>",
    },
    en: {
      header: "<h2 style={{ padding: 0, margin: 0 }}>Delivery-policy</h2>",
      body: "<ul><li><p>- The delivery time of the order is between (1) hour and (3) hours, and it may increase during peak times and seasons.</p><p>- You can follow up on orders. Through the website or by calling the hotline 01205977776.</p><p>- For any requests or inquiries regarding products or services, such as shipping and delivery, or complaints and suggestions, please write to us at info@alkhbaz.com</p></li></ul >",
    },
  },
  "return-policy": {
    type: "static",
    ar: {
      header: "<h2 style={{ padding: 0, margin: 0 }}>سياسة الاسترجاع </h2>",
      body: "<ul> <li> <p>تسري سياستنا هذه لمدة 3 أيام تقويمية من تاريخ الشراء. إذا تلقيت طلبك ولم تكن راضياً عنه لأي سبب من الأسباب يُمكنك إرجاع المنتج لاسترداد المبلغ المدفوع. إذا مر 3 أيام أو أكثر على شراءك للطب فلن يمكننا للأسف رد المبلغ المدفوع أو تبديل البضاعة.</p> </li> <li> <p>شروط الاسترداد</p> <p>يجب استيفاء المعايير التالية للتأهل لتبديل البضاعة:</p> <ul> <li>السلع القابلة للتلف مستثناة بشكل كامل من الإرجاع للمنتج و يختلف عن الوصف المذكور له</li> <li>يجب أن يكون المنتج لم يتم فتحه</li> <li>يجب أن يكون المنتج في أغلفته الأصلية</li> <li>يجب أن يكون المنتج لم يتم استخدامه</li> <li>يجب أن لا يكون قد الحق المنتج أي ضرر</li> <li>يتم إسترداد قيمة الاوردر بالنسبة لعملاء الفيزا بنفس طريقة السداد ويتم رد الطلب علي الحساب الذي تم الخصم علية</li> <li>يتم فحص جميع المرتجعات من أجل ضمان استيفاء المعايير المذكورة أعلاه. إذا كان المنتج لا يستوفي المعايير المذكورة أعلاه فإننا نحتفظ بالحق في عدم رد البضاعة.</li> </ul> </li> <li> <p>سياسة الألغاء</p> <p>من حق العميل ان يقوم بالغاء الطلب في خلال 15 دقيقة بعد عمل الطلب والرجوع الي الفرع تليفونياً لتأكيد الالغاء.</p> </li> <li> <p>المنتجات المشحونة</p> <p>&nbsp;</p> <ul> <li>مدة توصيل الطلب تكون في خلال فترة ما بين (1) ساعة الي (3) ساعات و من الممكن أن تزيد في أوقات الذروة وفي المواسم.</li> <li>تفضل بزيارةالفرع التابع له عملية الشراء بنا لإرجاع منتجاتك المشتراة من متجرنا على الإنترنت. سيقوم موظفونا بعملية إرجاع أو استبدال المنتجات المعنية الخاصة بك يجب أن تحرص على التأكد من أن البضائع قد تم تغليفها بشكل ملائم حتى لا تتضرر أثناء نقلها. إذا وصل المنتج إلينا تالفاً أو مستخدماً بما يتجاوز ما يلزمنا لفحصه بشكل معقول فقد نرفض عملية الرد.</li> </ul> </li> </ul>",
    },
    en: {
      header: "<h2 style={{ padding: 0, margin: 0 }}>Return-policy</h2>",
      body: "<ul> <li> <p>This policy is valid for 3 calendar days from the date of purchase. If you receive your order and are not satisfied with it for any reason, you can return the product for a refund. If 3 or more days have passed since your purchase of the medicine, unfortunately we cannot provide a refund or exchange of the merchandise.</p> </li> <li> <p>Refund Conditions</p> <p>The following criteria must be met to qualify for an exchange of merchandise: </p> <ul> <li>Perishable goods are completely excluded from return for a product that is different from its description</li> <li>The product must be unopened</li> <li>The product must be In its original packaging</li> <li>The product must not have been used</li> <li>The product must not have suffered any damage</li> <li>The order value will be refunded for Visa customers using the same payment method. The order will be refunded to the account that was deducted.</li> <li>All returns are examined in order to ensure that the above criteria are met. If the product does not meet the above criteria, we reserve the right not to return the goods.</li> </ul> </li> <li> <p>Cancellation Policy</p> <p>The customer has the right to cancel the order. Within 15 minutes after placing the order and returning to the branch by telephone to confirm the cancellation.</p> </li> <li> <p>Shipped products</p> <p>&nbsp;</p> <ul> <li>Duration The order will be delivered within a period of between (1) hour to (3) hours, and it may increase during peak times and seasons.</li> <li>Visit the branch to which the purchase process belongs to us to return your products purchased from our online store. Our staff will process the return or exchange of your concerned products. You must take care to ensure that the goods are properly packaged so that they are not damaged during transportation. If a product arrives to us damaged or used beyond what we reasonably need to inspect, we may decline a refund. </li> </ul> </li> </ul>",
    },
  },
  "f-and-q": {
    type: "accordion",
    ar: {
      header: "<h2 style={{ padding: 0, margin: 0 }}> الأسئلة الشائعة</h2>",
      body: [
        {
          question: "أنظمة العزل المائي المتاحة؟",
          answer:
            "<p>يوجد العديد من أنواع أنظمة العزل المائي المتاحة، ولكل منها مزاياها وعيوبها. وفيما يلي بعض الأنواع الأكثر شيوعًا:</p> <ol> <li>أنظمة العزل المائي بالأغشية الرقيقة: تتضمن هذه الأنظمة استخدام غشاء رقيق ومرن يتم تطبيقه على السطح المراد عزله. وتستخدم عادة للأسطح السطحية مثل الأسطح والشرفات.</li> <li>أنظمة العزل المائي بالأغشية السائلة: تتضمن هذه الأنظمة استخدام طلاء سائل يتم تطبيقه على السطح المراد عزله. وتستخدم عادة للأسطح السطحية مثل الأسطح والجدران والأساسات.</li> <li>أنظمة العزل المائي بالإسمنت: تتضمن هذه الأنظمة استخدام طلاء يعتمد على الإسمنت يتم تطبيقه على السطح المراد عزله. وتستخدم عادة للهياكل المصنوعة من الخرسانة مثل القبو وحوض السباحة.</li> <li>أنظمة العزل المائي بالبيتومين: تتضمن هذه الأنظمة استخدام طلاء يعتمد على بيتومين يتم تطبيقه على السطح المراد عزله. وتستخدم عادة للأسطح والأساسات.</li> <li>أنظمة العزل المائي بالأغشية السائلة بولي يوريثان: تتضمن هذه الأنظمة استخدام طلاء سائل يعتمد على بولي يوريثان يتم تطبيقه على السطح المراد عزله. وتستخدم عادة للأسطح السطحية مثل الأسطح والجدران والأساسات.</li> <li>أنظمة إسمنتية معدَّلة بالبوليمرات: تتضمن هذه الأنظمة استخدام طلاء يعتمد على إسمنت معدَّل بالبوليمرات لتحسين أدائه. وتستخدم عادة للهياكل المصنوعة من الخرسانة مثل القبو وحوض السباحة.</li> </ol> <p>هذه هي بعض أصناف أنظمة العزل المائي المختلفة التي يُستخدَمُ فيها كُلاً من نوعٍ من أصناف أغشية، أو طبقاتٍ سائِلَّةٍ، أو طبقاتٍ إسْفِنْجِيةٍ.</p>",
        },
        {
          question: "ما هو الفرق بين العزل الإيجابي و العزل السلبي؟",
          answer:
            "<p>يوجد العديد من أنواع أنظمة العزل المائي المتاحة، ولكل منها مزاياها وعيوبها. وفيما يلي بعض الأنواع الأكثر شيوعًا:</p> <ol> <li>أنظمة العزل المائي بالأغشية الرقيقة: تتضمن هذه الأنظمة استخدام غشاء رقيق ومرن يتم تطبيقه على السطح المراد عزله. وتستخدم عادة للأسطح السطحية مثل الأسطح والشرفات.</li> <li>أنظمة العزل المائي بالأغشية السائلة: تتضمن هذه الأنظمة استخدام طلاء سائل يتم تطبيقه على السطح المراد عزله. وتستخدم عادة للأسطح السطحية مثل الأسطح والجدران والأساسات.</li> <li>أنظمة العزل المائي بالإسمنت: تتضمن هذه الأنظمة استخدام طلاء يعتمد على الإسمنت يتم تطبيقه على السطح المراد عزله. وتستخدم عادة للهياكل المصنوعة من الخرسانة مثل القبو وحوض السباحة.</li> <li>أنظمة العزل المائي بالبيتومين: تتضمن هذه الأنظمة استخدام طلاء يعتمد على بيتومين يتم تطبيقه على السطح المراد عزله. وتستخدم عادة للأسطح والأساسات.</li> <li>أنظمة العزل المائي بالأغشية السائلة بولي يوريثان: تتضمن هذه الأنظمة استخدام طلاء سائل يعتمد على بولي يوريثان يتم تطبيقه على السطح المراد عزله. وتستخدم عادة للأسطح السطحية مثل الأسطح والجدران والأساسات.</li> <li>أنظمة إسمنتية معدَّلة بالبوليمرات: تتضمن هذه الأنظمة استخدام طلاء يعتمد على إسمنت معدَّل بالبوليمرات لتحسين أدائه. وتستخدم عادة للهياكل المصنوعة من الخرسانة مثل القبو وحوض السباحة.</li> </ol> <p>هذه هي بعض أصناف أنظمة العزل المائي المختلفة التي يُستخدَمُ فيها كُلاً من نوعٍ من أصناف أغشية، أو طبقاتٍ سائِلَّةٍ، أو طبقاتٍ إسْفِنْجِيةٍ.</p>",
        },
        {
          question: "العزل المائي حلول تقنية لمشاكل شائعة؟",
          answer:
            "<p>يوجد العديد من أنواع أنظمة العزل المائي المتاحة، ولكل منها مزاياها وعيوبها. وفيما يلي بعض الأنواع الأكثر شيوعًا:</p> <ol> <li>أنظمة العزل المائي بالأغشية الرقيقة: تتضمن هذه الأنظمة استخدام غشاء رقيق ومرن يتم تطبيقه على السطح المراد عزله. وتستخدم عادة للأسطح السطحية مثل الأسطح والشرفات.</li> <li>أنظمة العزل المائي بالأغشية السائلة: تتضمن هذه الأنظمة استخدام طلاء سائل يتم تطبيقه على السطح المراد عزله. وتستخدم عادة للأسطح السطحية مثل الأسطح والجدران والأساسات.</li> <li>أنظمة العزل المائي بالإسمنت: تتضمن هذه الأنظمة استخدام طلاء يعتمد على الإسمنت يتم تطبيقه على السطح المراد عزله. وتستخدم عادة للهياكل المصنوعة من الخرسانة مثل القبو وحوض السباحة.</li> <li>أنظمة العزل المائي بالبيتومين: تتضمن هذه الأنظمة استخدام طلاء يعتمد على بيتومين يتم تطبيقه على السطح المراد عزله. وتستخدم عادة للأسطح والأساسات.</li> <li>أنظمة العزل المائي بالأغشية السائلة بولي يوريثان: تتضمن هذه الأنظمة استخدام طلاء سائل يعتمد على بولي يوريثان يتم تطبيقه على السطح المراد عزله. وتستخدم عادة للأسطح السطحية مثل الأسطح والجدران والأساسات.</li> <li>أنظمة إسمنتية معدَّلة بالبوليمرات: تتضمن هذه الأنظمة استخدام طلاء يعتمد على إسمنت معدَّل بالبوليمرات لتحسين أدائه. وتستخدم عادة للهياكل المصنوعة من الخرسانة مثل القبو وحوض السباحة.</li> </ol> <p>هذه هي بعض أصناف أنظمة العزل المائي المختلفة التي يُستخدَمُ فيها كُلاً من نوعٍ من أصناف أغشية، أو طبقاتٍ سائِلَّةٍ، أو طبقاتٍ إسْفِنْجِيةٍ.</p>",
        },
        {
          question:
            "ما هي خدمة العزل التي تقدمها شمس البوادي باستخدام البوليوريا؟",
          answer:
            "<p>يوجد العديد من أنواع أنظمة العزل المائي المتاحة، ولكل منها مزاياها وعيوبها. وفيما يلي بعض الأنواع الأكثر شيوعًا:</p> <ol> <li>أنظمة العزل المائي بالأغشية الرقيقة: تتضمن هذه الأنظمة استخدام غشاء رقيق ومرن يتم تطبيقه على السطح المراد عزله. وتستخدم عادة للأسطح السطحية مثل الأسطح والشرفات.</li> <li>أنظمة العزل المائي بالأغشية السائلة: تتضمن هذه الأنظمة استخدام طلاء سائل يتم تطبيقه على السطح المراد عزله. وتستخدم عادة للأسطح السطحية مثل الأسطح والجدران والأساسات.</li> <li>أنظمة العزل المائي بالإسمنت: تتضمن هذه الأنظمة استخدام طلاء يعتمد على الإسمنت يتم تطبيقه على السطح المراد عزله. وتستخدم عادة للهياكل المصنوعة من الخرسانة مثل القبو وحوض السباحة.</li> <li>أنظمة العزل المائي بالبيتومين: تتضمن هذه الأنظمة استخدام طلاء يعتمد على بيتومين يتم تطبيقه على السطح المراد عزله. وتستخدم عادة للأسطح والأساسات.</li> <li>أنظمة العزل المائي بالأغشية السائلة بولي يوريثان: تتضمن هذه الأنظمة استخدام طلاء سائل يعتمد على بولي يوريثان يتم تطبيقه على السطح المراد عزله. وتستخدم عادة للأسطح السطحية مثل الأسطح والجدران والأساسات.</li> <li>أنظمة إسمنتية معدَّلة بالبوليمرات: تتضمن هذه الأنظمة استخدام طلاء يعتمد على إسمنت معدَّل بالبوليمرات لتحسين أدائه. وتستخدم عادة للهياكل المصنوعة من الخرسانة مثل القبو وحوض السباحة.</li> </ol> <p>هذه هي بعض أصناف أنظمة العزل المائي المختلفة التي يُستخدَمُ فيها كُلاً من نوعٍ من أصناف أغشية، أو طبقاتٍ سائِلَّةٍ، أو طبقاتٍ إسْفِنْجِيةٍ.</p>",
        },
        {
          question: "ما هي الخرسانة الرغوية وكيف تصنع؟",
          answer:
            "<p>يوجد العديد من أنواع أنظمة العزل المائي المتاحة، ولكل منها مزاياها وعيوبها. وفيما يلي بعض الأنواع الأكثر شيوعًا:</p> <ol> <li>أنظمة العزل المائي بالأغشية الرقيقة: تتضمن هذه الأنظمة استخدام غشاء رقيق ومرن يتم تطبيقه على السطح المراد عزله. وتستخدم عادة للأسطح السطحية مثل الأسطح والشرفات.</li> <li>أنظمة العزل المائي بالأغشية السائلة: تتضمن هذه الأنظمة استخدام طلاء سائل يتم تطبيقه على السطح المراد عزله. وتستخدم عادة للأسطح السطحية مثل الأسطح والجدران والأساسات.</li> <li>أنظمة العزل المائي بالإسمنت: تتضمن هذه الأنظمة استخدام طلاء يعتمد على الإسمنت يتم تطبيقه على السطح المراد عزله. وتستخدم عادة للهياكل المصنوعة من الخرسانة مثل القبو وحوض السباحة.</li> <li>أنظمة العزل المائي بالبيتومين: تتضمن هذه الأنظمة استخدام طلاء يعتمد على بيتومين يتم تطبيقه على السطح المراد عزله. وتستخدم عادة للأسطح والأساسات.</li> <li>أنظمة العزل المائي بالأغشية السائلة بولي يوريثان: تتضمن هذه الأنظمة استخدام طلاء سائل يعتمد على بولي يوريثان يتم تطبيقه على السطح المراد عزله. وتستخدم عادة للأسطح السطحية مثل الأسطح والجدران والأساسات.</li> <li>أنظمة إسمنتية معدَّلة بالبوليمرات: تتضمن هذه الأنظمة استخدام طلاء يعتمد على إسمنت معدَّل بالبوليمرات لتحسين أدائه. وتستخدم عادة للهياكل المصنوعة من الخرسانة مثل القبو وحوض السباحة.</li> </ol> <p>هذه هي بعض أصناف أنظمة العزل المائي المختلفة التي يُستخدَمُ فيها كُلاً من نوعٍ من أصناف أغشية، أو طبقاتٍ سائِلَّةٍ، أو طبقاتٍ إسْفِنْجِيةٍ.</p>",
        },
        {
          question: "كيفية تحسين جودة مشاريع البناء",
          answer:
            "<p>يوجد العديد من أنواع أنظمة العزل المائي المتاحة، ولكل منها مزاياها وعيوبها. وفيما يلي بعض الأنواع الأكثر شيوعًا:</p> <ol> <li>أنظمة العزل المائي بالأغشية الرقيقة: تتضمن هذه الأنظمة استخدام غشاء رقيق ومرن يتم تطبيقه على السطح المراد عزله. وتستخدم عادة للأسطح السطحية مثل الأسطح والشرفات.</li> <li>أنظمة العزل المائي بالأغشية السائلة: تتضمن هذه الأنظمة استخدام طلاء سائل يتم تطبيقه على السطح المراد عزله. وتستخدم عادة للأسطح السطحية مثل الأسطح والجدران والأساسات.</li> <li>أنظمة العزل المائي بالإسمنت: تتضمن هذه الأنظمة استخدام طلاء يعتمد على الإسمنت يتم تطبيقه على السطح المراد عزله. وتستخدم عادة للهياكل المصنوعة من الخرسانة مثل القبو وحوض السباحة.</li> <li>أنظمة العزل المائي بالبيتومين: تتضمن هذه الأنظمة استخدام طلاء يعتمد على بيتومين يتم تطبيقه على السطح المراد عزله. وتستخدم عادة للأسطح والأساسات.</li> <li>أنظمة العزل المائي بالأغشية السائلة بولي يوريثان: تتضمن هذه الأنظمة استخدام طلاء سائل يعتمد على بولي يوريثان يتم تطبيقه على السطح المراد عزله. وتستخدم عادة للأسطح السطحية مثل الأسطح والجدران والأساسات.</li> <li>أنظمة إسمنتية معدَّلة بالبوليمرات: تتضمن هذه الأنظمة استخدام طلاء يعتمد على إسمنت معدَّل بالبوليمرات لتحسين أدائه. وتستخدم عادة للهياكل المصنوعة من الخرسانة مثل القبو وحوض السباحة.</li> </ol> <p>هذه هي بعض أصناف أنظمة العزل المائي المختلفة التي يُستخدَمُ فيها كُلاً من نوعٍ من أصناف أغشية، أو طبقاتٍ سائِلَّةٍ، أو طبقاتٍ إسْفِنْجِيةٍ.</p>",
        },
        {
          question: "ما هي الخدمات التي تقدمها شمس البوادي لأنظمة العزل",
          answer:
            "<p>يوجد العديد من أنواع أنظمة العزل المائي المتاحة، ولكل منها مزاياها وعيوبها. وفيما يلي بعض الأنواع الأكثر شيوعًا:</p> <ol> <li>أنظمة العزل المائي بالأغشية الرقيقة: تتضمن هذه الأنظمة استخدام غشاء رقيق ومرن يتم تطبيقه على السطح المراد عزله. وتستخدم عادة للأسطح السطحية مثل الأسطح والشرفات.</li> <li>أنظمة العزل المائي بالأغشية السائلة: تتضمن هذه الأنظمة استخدام طلاء سائل يتم تطبيقه على السطح المراد عزله. وتستخدم عادة للأسطح السطحية مثل الأسطح والجدران والأساسات.</li> <li>أنظمة العزل المائي بالإسمنت: تتضمن هذه الأنظمة استخدام طلاء يعتمد على الإسمنت يتم تطبيقه على السطح المراد عزله. وتستخدم عادة للهياكل المصنوعة من الخرسانة مثل القبو وحوض السباحة.</li> <li>أنظمة العزل المائي بالبيتومين: تتضمن هذه الأنظمة استخدام طلاء يعتمد على بيتومين يتم تطبيقه على السطح المراد عزله. وتستخدم عادة للأسطح والأساسات.</li> <li>أنظمة العزل المائي بالأغشية السائلة بولي يوريثان: تتضمن هذه الأنظمة استخدام طلاء سائل يعتمد على بولي يوريثان يتم تطبيقه على السطح المراد عزله. وتستخدم عادة للأسطح السطحية مثل الأسطح والجدران والأساسات.</li> <li>أنظمة إسمنتية معدَّلة بالبوليمرات: تتضمن هذه الأنظمة استخدام طلاء يعتمد على إسمنت معدَّل بالبوليمرات لتحسين أدائه. وتستخدم عادة للهياكل المصنوعة من الخرسانة مثل القبو وحوض السباحة.</li> </ol> <p>هذه هي بعض أصناف أنظمة العزل المائي المختلفة التي يُستخدَمُ فيها كُلاً من نوعٍ من أصناف أغشية، أو طبقاتٍ سائِلَّةٍ، أو طبقاتٍ إسْفِنْجِيةٍ.</p>",
        },
        {
          question:
            "ما هي خدمة العزل التي تقدمها شمس البوادي باستخدام البوليوريا؟",
          answer:
            "<p>يوجد العديد من أنواع أنظمة العزل المائي المتاحة، ولكل منها مزاياها وعيوبها. وفيما يلي بعض الأنواع الأكثر شيوعًا:</p> <ol> <li>أنظمة العزل المائي بالأغشية الرقيقة: تتضمن هذه الأنظمة استخدام غشاء رقيق ومرن يتم تطبيقه على السطح المراد عزله. وتستخدم عادة للأسطح السطحية مثل الأسطح والشرفات.</li> <li>أنظمة العزل المائي بالأغشية السائلة: تتضمن هذه الأنظمة استخدام طلاء سائل يتم تطبيقه على السطح المراد عزله. وتستخدم عادة للأسطح السطحية مثل الأسطح والجدران والأساسات.</li> <li>أنظمة العزل المائي بالإسمنت: تتضمن هذه الأنظمة استخدام طلاء يعتمد على الإسمنت يتم تطبيقه على السطح المراد عزله. وتستخدم عادة للهياكل المصنوعة من الخرسانة مثل القبو وحوض السباحة.</li> <li>أنظمة العزل المائي بالبيتومين: تتضمن هذه الأنظمة استخدام طلاء يعتمد على بيتومين يتم تطبيقه على السطح المراد عزله. وتستخدم عادة للأسطح والأساسات.</li> <li>أنظمة العزل المائي بالأغشية السائلة بولي يوريثان: تتضمن هذه الأنظمة استخدام طلاء سائل يعتمد على بولي يوريثان يتم تطبيقه على السطح المراد عزله. وتستخدم عادة للأسطح السطحية مثل الأسطح والجدران والأساسات.</li> <li>أنظمة إسمنتية معدَّلة بالبوليمرات: تتضمن هذه الأنظمة استخدام طلاء يعتمد على إسمنت معدَّل بالبوليمرات لتحسين أدائه. وتستخدم عادة للهياكل المصنوعة من الخرسانة مثل القبو وحوض السباحة.</li> </ol> <p>هذه هي بعض أصناف أنظمة العزل المائي المختلفة التي يُستخدَمُ فيها كُلاً من نوعٍ من أصناف أغشية، أو طبقاتٍ سائِلَّةٍ، أو طبقاتٍ إسْفِنْجِيةٍ.</p>",
        },
        {
          question:
            "العلاقة بين المالك والاستشاري والمقاول ، وكيفية الاختيار للمواصفات ",
          answer:
            "<p>يوجد العديد من أنواع أنظمة العزل المائي المتاحة، ولكل منها مزاياها وعيوبها. وفيما يلي بعض الأنواع الأكثر شيوعًا:</p> <ol> <li>أنظمة العزل المائي بالأغشية الرقيقة: تتضمن هذه الأنظمة استخدام غشاء رقيق ومرن يتم تطبيقه على السطح المراد عزله. وتستخدم عادة للأسطح السطحية مثل الأسطح والشرفات.</li> <li>أنظمة العزل المائي بالأغشية السائلة: تتضمن هذه الأنظمة استخدام طلاء سائل يتم تطبيقه على السطح المراد عزله. وتستخدم عادة للأسطح السطحية مثل الأسطح والجدران والأساسات.</li> <li>أنظمة العزل المائي بالإسمنت: تتضمن هذه الأنظمة استخدام طلاء يعتمد على الإسمنت يتم تطبيقه على السطح المراد عزله. وتستخدم عادة للهياكل المصنوعة من الخرسانة مثل القبو وحوض السباحة.</li> <li>أنظمة العزل المائي بالبيتومين: تتضمن هذه الأنظمة استخدام طلاء يعتمد على بيتومين يتم تطبيقه على السطح المراد عزله. وتستخدم عادة للأسطح والأساسات.</li> <li>أنظمة العزل المائي بالأغشية السائلة بولي يوريثان: تتضمن هذه الأنظمة استخدام طلاء سائل يعتمد على بولي يوريثان يتم تطبيقه على السطح المراد عزله. وتستخدم عادة للأسطح السطحية مثل الأسطح والجدران والأساسات.</li> <li>أنظمة إسمنتية معدَّلة بالبوليمرات: تتضمن هذه الأنظمة استخدام طلاء يعتمد على إسمنت معدَّل بالبوليمرات لتحسين أدائه. وتستخدم عادة للهياكل المصنوعة من الخرسانة مثل القبو وحوض السباحة.</li> </ol> <p>هذه هي بعض أصناف أنظمة العزل المائي المختلفة التي يُستخدَمُ فيها كُلاً من نوعٍ من أصناف أغشية، أو طبقاتٍ سائِلَّةٍ، أو طبقاتٍ إسْفِنْجِيةٍ.</p>",
        },
      ],
    },
    en: {
      header:
        "<h2 style={{ padding: 0, margin: 0 }}>Frequently Asked Questions</h2>",
      body: [
        {
          question: "Waterproofing systems available?",
          answer:
            "<p>There are many types of waterproofing systems available, each with their own advantages and disadvantages. Here are some of the most common types:</p> <ol> <li>Thin film waterproofing systems: These systems involve the use of a thin, flexible membrane that is applied On the surface to be insulated. They are usually used for superficial surfaces such as roofs and balconies.</li> <li>Liquid membrane waterproofing systems: These systems involve the use of a liquid paint applied to the surface to be insulated. They are usually used for superficial surfaces such as roofs, walls, and foundations.</li> li> <li>Cement waterproofing systems: These systems involve the use of a cement-based coating applied to the surface to be insulated. They are usually used for structures made of concrete such as basements and swimming pools.</li> <li>Bitumen waterproofing systems: These include The systems use a bitumen-based paint that is applied to the surface to be insulated. They are usually used for roofs and foundations.</li> <li>Polyurethane liquid membrane waterproofing systems: These systems include the use of a liquid polyurethane-based paint that is applied to the surface to be insulated. They are typically used for superficial surfaces such as roofs, walls, and foundations.</li> <li>Polymer modified cement systems: These systems involve the use of a coating based on polymer modified cement to improve its performance. They are commonly used for concrete structures such as basements and swimming pools.</li> </ol> <p>These are some of the different types of waterproofing systems in which some type of membrane, liquid layer or foam layer is used.</li> </ol> <p>These are some of the different types of waterproofing systems in which some type of membrane, liquid layer or foam layer is used. p>",
        },
        {
          question:
            "What is the difference between positive insulation and negative insulation?",
          answer:
            "<p>There are many types of waterproofing systems available, each with their own advantages and disadvantages. Here are some of the most common types:</p> <ol> <li>Thin film waterproofing systems: These systems involve the use of a thin, flexible membrane that is applied On the surface to be insulated. They are usually used for superficial surfaces such as roofs and balconies.</li> <li>Liquid membrane waterproofing systems: These systems involve the use of a liquid paint applied to the surface to be insulated. They are usually used for superficial surfaces such as roofs, walls, and foundations.</li> li> <li>Cement waterproofing systems: These systems involve the use of a cement-based coating applied to the surface to be insulated. They are usually used for structures made of concrete such as basements and swimming pools.</li> <li>Bitumen waterproofing systems: These include The systems use a bitumen-based paint that is applied to the surface to be insulated. They are usually used for roofs and foundations.</li> <li>Polyurethane liquid membrane waterproofing systems: These systems include the use of a liquid polyurethane-based paint that is applied to the surface to be insulated. They are typically used for superficial surfaces such as roofs, walls, and foundations.</li> <li>Polymer modified cement systems: These systems involve the use of a coating based on polymer modified cement to improve its performance. They are commonly used for concrete structures such as basements and swimming pools.</li> </ol> <p>These are some of the different types of waterproofing systems in which some type of membrane, liquid layer or foam layer is used.</li> </ol> <p>These are some of the different types of waterproofing systems in which some type of membrane, liquid layer or foam layer is used. p>",
        },
        {
          question: "Waterproofing Technical solutions to common problems?",
          answer:
            "<p>There are many types of waterproofing systems available, each with their own advantages and disadvantages. Here are some of the most common types:</p> <ol> <li>Thin film waterproofing systems: These systems involve the use of a thin, flexible membrane that is applied On the surface to be insulated. They are usually used for superficial surfaces such as roofs and balconies.</li> <li>Liquid membrane waterproofing systems: These systems involve the use of a liquid paint applied to the surface to be insulated. They are usually used for superficial surfaces such as roofs, walls, and foundations.</li> li> <li>Cement waterproofing systems: These systems involve the use of a cement-based coating applied to the surface to be insulated. They are usually used for structures made of concrete such as basements and swimming pools.</li> <li>Bitumen waterproofing systems: These include The systems use a bitumen-based paint that is applied to the surface to be insulated. They are usually used for roofs and foundations.</li> <li>Polyurethane liquid membrane waterproofing systems: These systems include the use of a liquid polyurethane-based paint that is applied to the surface to be insulated. They are typically used for superficial surfaces such as roofs, walls, and foundations.</li> <li>Polymer modified cement systems: These systems involve the use of a coating based on polymer modified cement to improve its performance. They are commonly used for concrete structures such as basements and swimming pools.</li> </ol> <p>These are some of the different types of waterproofing systems in which some type of membrane, liquid layer or foam layer is used.</li> </ol> <p>These are some of the different types of waterproofing systems in which some type of membrane, liquid layer or foam layer is used. p>",
        },
        {
          question:
            "What is the insulation service provided by Shams Al Bawadi using polyurea?",
          answer:
            "<p>There are many types of waterproofing systems available, each with their own advantages and disadvantages. Here are some of the most common types:</p> <ol> <li>Thin film waterproofing systems: These systems involve the use of a thin, flexible membrane that is applied On the surface to be insulated. They are usually used for superficial surfaces such as roofs and balconies.</li> <li>Liquid membrane waterproofing systems: These systems involve the use of a liquid paint applied to the surface to be insulated. They are usually used for superficial surfaces such as roofs, walls, and foundations.</li> li> <li>Cement waterproofing systems: These systems involve the use of a cement-based coating applied to the surface to be insulated. They are usually used for structures made of concrete such as basements and swimming pools.</li> <li>Bitumen waterproofing systems: These include The systems use a bitumen-based paint that is applied to the surface to be insulated. They are usually used for roofs and foundations.</li> <li>Polyurethane liquid membrane waterproofing systems: These systems include the use of a liquid polyurethane-based paint that is applied to the surface to be insulated. They are typically used for superficial surfaces such as roofs, walls, and foundations.</li> <li>Polymer modified cement systems: These systems involve the use of a coating based on polymer modified cement to improve its performance. They are commonly used for concrete structures such as basements and swimming pools.</li> </ol> <p>These are some of the different types of waterproofing systems in which some type of membrane, liquid layer or foam layer is used.</li> </ol> <p>These are some of the different types of waterproofing systems in which some type of membrane, liquid layer or foam layer is used. p>",
        },
        {
          question: "What is foam concrete and how is it made?",
          answer:
            "<p>There are many types of waterproofing systems available, each with their own advantages and disadvantages. Here are some of the most common types:</p> <ol> <li>Thin film waterproofing systems: These systems involve the use of a thin, flexible membrane that is applied On the surface to be insulated. They are usually used for superficial surfaces such as roofs and balconies.</li> <li>Liquid membrane waterproofing systems: These systems involve the use of a liquid paint applied to the surface to be insulated. They are usually used for superficial surfaces such as roofs, walls, and foundations.</li> li> <li>Cement waterproofing systems: These systems involve the use of a cement-based coating applied to the surface to be insulated. They are usually used for structures made of concrete such as basements and swimming pools.</li> <li>Bitumen waterproofing systems: These include The systems use a bitumen-based paint that is applied to the surface to be insulated. They are usually used for roofs and foundations.</li> <li>Polyurethane liquid membrane waterproofing systems: These systems include the use of a liquid polyurethane-based paint that is applied to the surface to be insulated. They are typically used for superficial surfaces such as roofs, walls, and foundations.</li> <li>Polymer modified cement systems: These systems involve the use of a coating based on polymer modified cement to improve its performance. They are commonly used for concrete structures such as basements and swimming pools.</li> </ol> <p>These are some of the different types of waterproofing systems in which some type of membrane, liquid layer or foam layer is used.</li> </ol> <p>These are some of the different types of waterproofing systems in which some type of membrane, liquid layer or foam layer is used. p>",
        },
        {
          question: "How to improve the quality of construction projects",
          answer:
            "<p>There are many types of waterproofing systems available, each with their own advantages and disadvantages. Here are some of the most common types:</p> <ol> <li>Thin film waterproofing systems: These systems involve the use of a thin, flexible membrane that is applied On the surface to be insulated. They are usually used for superficial surfaces such as roofs and balconies.</li> <li>Liquid membrane waterproofing systems: These systems involve the use of a liquid paint applied to the surface to be insulated. They are usually used for superficial surfaces such as roofs, walls, and foundations.</li> li> <li>Cement waterproofing systems: These systems involve the use of a cement-based coating applied to the surface to be insulated. They are usually used for structures made of concrete such as basements and swimming pools.</li> <li>Bitumen waterproofing systems: These include The systems use a bitumen-based paint that is applied to the surface to be insulated. They are usually used for roofs and foundations.</li> <li>Polyurethane liquid membrane waterproofing systems: These systems include the use of a liquid polyurethane-based paint that is applied to the surface to be insulated. They are typically used for superficial surfaces such as roofs, walls, and foundations.</li> <li>Polymer modified cement systems: These systems involve the use of a coating based on polymer modified cement to improve its performance. They are commonly used for concrete structures such as basements and swimming pools.</li> </ol> <p>These are some of the different types of waterproofing systems in which some type of membrane, liquid layer or foam layer is used.</li> </ol> <p>These are some of the different types of waterproofing systems in which some type of membrane, liquid layer or foam layer is used. p>",
        },
        {
          question:
            "What services does Shams Al Bawadi provide for insulation systems?",
          answer:
            "<p>There are many types of waterproofing systems available, each with their own advantages and disadvantages. Here are some of the most common types:</p> <ol> <li>Thin film waterproofing systems: These systems involve the use of a thin, flexible membrane that is applied On the surface to be insulated. They are usually used for superficial surfaces such as roofs and balconies.</li> <li>Liquid membrane waterproofing systems: These systems involve the use of a liquid paint applied to the surface to be insulated. They are usually used for superficial surfaces such as roofs, walls, and foundations.</li> li> <li>Cement waterproofing systems: These systems involve the use of a cement-based coating applied to the surface to be insulated. They are usually used for structures made of concrete such as basements and swimming pools.</li> <li>Bitumen waterproofing systems: These include The systems use a bitumen-based paint that is applied to the surface to be insulated. They are usually used for roofs and foundations.</li> <li>Polyurethane liquid membrane waterproofing systems: These systems include the use of a liquid polyurethane-based paint that is applied to the surface to be insulated. They are typically used for superficial surfaces such as roofs, walls, and foundations.</li> <li>Polymer modified cement systems: These systems involve the use of a coating based on polymer modified cement to improve its performance. They are commonly used for concrete structures such as basements and swimming pools.</li> </ol> <p>These are some of the different types of waterproofing systems in which some type of membrane, liquid layer or foam layer is used.</li> </ol> <p>These are some of the different types of waterproofing systems in which some type of membrane, liquid layer or foam layer is used. p>",
        },
        {
          question:
            "What is the insulation service provided by Shams Al Bawadi using polyurea?",
          answer:
            "<p>There are many types of waterproofing systems available, each with their own advantages and disadvantages. Here are some of the most common types:</p> <ol> <li>Thin film waterproofing systems: These systems involve the use of a thin, flexible membrane that is applied On the surface to be insulated. They are usually used for superficial surfaces such as roofs and balconies.</li> <li>Liquid membrane waterproofing systems: These systems involve the use of a liquid paint applied to the surface to be insulated. They are usually used for superficial surfaces such as roofs, walls, and foundations.</li> li> <li>Cement waterproofing systems: These systems involve the use of a cement-based coating applied to the surface to be insulated. They are usually used for structures made of concrete such as basements and swimming pools.</li> <li>Bitumen waterproofing systems: These include The systems use a bitumen-based paint that is applied to the surface to be insulated. They are usually used for roofs and foundations.</li> <li>Polyurethane liquid membrane waterproofing systems: These systems include the use of a liquid polyurethane-based paint that is applied to the surface to be insulated. They are typically used for superficial surfaces such as roofs, walls, and foundations.</li> <li>Polymer modified cement systems: These systems involve the use of a coating based on polymer modified cement to improve its performance. They are commonly used for concrete structures such as basements and swimming pools.</li> </ol> <p>These are some of the different types of waterproofing systems in which some type of membrane, liquid layer or foam layer is used.</li> </ol> <p>These are some of the different types of waterproofing systems in which some type of membrane, liquid layer or foam layer is used. p>",
        },
        {
          question:
            "The relationship between the owner, consultant and contractor, and how to choose according to specifications",
          answer:
            "<p>There are many types of waterproofing systems available, each with their own advantages and disadvantages. Here are some of the most common types:</p> <ol> <li>Thin film waterproofing systems: These systems involve the use of a thin, flexible membrane that is applied On the surface to be insulated. They are usually used for superficial surfaces such as roofs and balconies.</li> <li>Liquid membrane waterproofing systems: These systems involve the use of a liquid paint applied to the surface to be insulated. They are usually used for superficial surfaces such as roofs, walls, and foundations.</li> li> <li>Cement waterproofing systems: These systems involve the use of a cement-based coating applied to the surface to be insulated. They are usually used for structures made of concrete such as basements and swimming pools.</li> <li>Bitumen waterproofing systems: These include The systems use a bitumen-based paint that is applied to the surface to be insulated. They are usually used for roofs and foundations.</li> <li>Polyurethane liquid membrane waterproofing systems: These systems include the use of a liquid polyurethane-based paint that is applied to the surface to be insulated. They are typically used for superficial surfaces such as roofs, walls, and foundations.</li> <li>Polymer modified cement systems: These systems involve the use of a coating based on polymer modified cement to improve its performance. They are commonly used for concrete structures such as basements and swimming pools.</li> </ol> <p>These are some of the different types of waterproofing systems in which some type of membrane, liquid layer or foam layer is used.</li> </ol> <p>These are some of the different types of waterproofing systems in which some type of membrane, liquid layer or foam layer is used. p>",
        },
      ],
    },
  },
};
